version: "3.8"

services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    command: [ "supervisord", "-n" ]
    build:
      context: images/${PHP_DIR}
      args:
        PHP_VERSION: ${PHP_VERSION}
        SET_UP_SSH_SERVER: "${SET_UP_SSH_SERVER}"
        SET_UP_MAILHOG: "${SET_UP_MAILHOG}"
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        XDEBUG_VERSION: ${XDEBUG_VERSION}
        XDEBUG_MODE: ${XDEBUG_MODE:-debug}
        PHP_MBSTRING_FUNC_OVERLOAD: ${PHP_MBSTRING_FUNC_OVERLOAD}
        SET_UP_MEMCACHE: "${SET_UP_MEMCACHE}"
        MEMCACHE_VERSION: ${MEMCACHE_VERSION}
        USER_ID: ${USER_ID:-1000}
        GROUP: ${GROUP:-www-data}
    volumes:
      - ~/.ssh:/var/www/.ssh
      - ./tmp/php_sessions:/sessions
      - logs:/var/log
      - project:/var/www
    ports:
      - "${INTERFACE:-127.0.0.1}:${PHP_FPM_PORT:-9000}:9000"
      - "${INTERFACE:-127.0.0.1}:${SSH_PORT:-2222}:22"
    environment:
      XDEBUG_CONFIG: "discover_client_host=${XDEBUG_DISCOVER_CLIENT_HOST} start_with_request=${XDEBUG_START_WITH_REQUEST} client_host=${XDEBUG_HOST} client_port=${XDEBUG_PORT}"
      PHP_IDE_CONFIG: "serverName=${SERVER_NAME}"
    networks:
      - app-network

  mailhog:
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    image: mailhog/mailhog
    ports:
      - "${INTERFACE:-127.0.0.1}:${MAILHOG_SMPT_PORT:-1025}:1025" # smtp server
      - "${INTERFACE:-127.0.0.1}:${MAILHOG_WEB_PORT:-1025}:8025" # web ui
    networks:
      - app-network

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: images/nginx
      args:
        DOMAIN: ${DOMAIN}
        REGEXP: ${NGINX_ROOT_REGEXP}
        CONDITION_NUMBER: ${NGINX_ROOT_CONDITION_NUMBER}
    volumes:
      - project:/var/www
      - logs:/var/log
    ports:
      - "${INTERFACE:-127.0.0.1}:80:80"
      - "${INTERFACE:-127.0.0.1}:443:443"
    networks:
      - app-network

  database:
    container_name: ${COMPOSE_PROJECT_NAME}_database
    build:
      context: images/database
      args:
        DB_VERSION: ${DB_VERSION}
        DB_TYPE: ${DB_TYPE}
    ports:
      - "${INTERFACE:-127.0.0.1}:${DB_PORT:-3306}:3306"
    networks:
      - app-network
    volumes:
      - ./images/database/conf.d/base.cnf:/etc/mysql/conf.d/base.cnf
      - logs:/var/log
      - project:/var/www
      - ${DATA_PATH}/database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_BITRIX}

  memcached:
    image: memcached:1.6.12-alpine
    ports:
      - '${INTERFACE:-127.0.0.1}:11211:11211'
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  project:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_PATH}
  logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${LOGS_PATH}
